/**
 * Build step: reads content/products/*.json (the CMS-managed source of truth)
 * and regenerates everything else:
 *   - Inlines `const PRODUCTS = [...]` and `const VARIANTS = {...}` in index.html
 *   - Writes data/products.json (slim, server-authoritative for Stripe)
 *   - Writes data/variant-prices.clean.json (variant validation for Stripe)
 *
 * Runs on every Netlify deploy. Idempotent — running locally produces the same
 * output that Netlify would deploy.
 *
 * Conventions:
 *   - Product ID = filename without `.json`. Auto-generated by Decap from the
 *     product name slug, so collisions are impossible.
 *   - `available: false` products are hidden from the public site (filtered out
 *     of PRODUCTS, data/products.json, and data/variant-prices.clean.json).
 *   - Sort order = `created` desc (newest first).
 */

const fs = require('fs');
const path = require('path');

const ROOT      = path.join(__dirname, '..');
const CONTENT   = path.join(ROOT, 'content', 'products');
const INDEX     = path.join(ROOT, 'index.html');
const OUT_PROD  = path.join(ROOT, 'data', 'products.json');
const OUT_VAR   = path.join(ROOT, 'data', 'variant-prices.clean.json');

// ───── Load + filter ─────
const files = fs.readdirSync(CONTENT).filter(f => f.endsWith('.json'));
const allProducts = files.map(f => {
  const data = JSON.parse(fs.readFileSync(path.join(CONTENT, f), 'utf-8'));
  return { ...data, id: f.replace(/\.json$/, '') };
});

// Hide unavailable from the public site. They stay in content/ so wife can
// re-list them by toggling Available back on in the CMS.
const products = allProducts
  .filter(p => p.available !== false)
  .sort((a, b) => {
    // Newest first — fall back to id-desc if `created` missing.
    const ac = a.created ? Date.parse(a.created) : 0;
    const bc = b.created ? Date.parse(b.created) : 0;
    if (ac !== bc) return bc - ac;
    return String(b.id).localeCompare(String(a.id));
  });

if (!products.length) {
  console.error('❌ No available products found in content/products/');
  process.exit(1);
}

// ───── Helpers ─────
function escapeJsString(s) {
  return JSON.stringify(s);
}
function arrLit(arr) {
  return '[' + arr.map(escapeJsString).join(',') + ']';
}
// Decap's tag-list widget stores values as a CSV string. Accept either form.
function toTagArray(v) {
  if (Array.isArray(v)) return v.filter(Boolean);
  if (typeof v === 'string') return v.split(',').map(s => s.trim()).filter(Boolean);
  return [];
}

// ───── Build inline PRODUCTS array ─────
const productLines = products.map(p => {
  const fields = [
    `id:${escapeJsString(p.id)}`,
    `name:${escapeJsString(p.name)}`,
    `price:${typeof p.price === 'number' ? p.price : 0}`,
    `image:${escapeJsString(p.image || '')}`,
    `chakra:${arrLit(p.chakra || [])}`,
    `properties:${arrLit(toTagArray(p.properties))}`,
  ];
  if (p.description) fields.push(`description:${escapeJsString(p.description)}`);
  return `  { ${fields.join(', ')} }`;
});

const productsBlock =
  'const PRODUCTS = [\n' +
  productLines.join(',\n') +
  '\n];';

// ───── Build inline VARIANTS object ─────
const variantsObj = {};
for (const p of products) {
  if (Array.isArray(p.variants) && p.variants.length) {
    variantsObj[p.id] = p.variants.map(v => ({
      n: v.name,
      p: typeof v.price === 'number' ? v.price : 0,
      a: !!v.available,
      // Full URL (or path). variantImgUrl in index.html returns it as-is.
      i: v.image || '',
    }));
  }
}
const variantsBlock = 'const VARIANTS = ' + JSON.stringify(variantsObj) + ';';

// ───── Write index.html with both blocks replaced ─────
let html = fs.readFileSync(INDEX, 'utf-8');

const productsRe = /const PRODUCTS\s*=\s*\[[\s\S]*?\n\];/;
if (!productsRe.test(html)) {
  console.error('❌ Could not find PRODUCTS array in index.html');
  process.exit(1);
}
html = html.replace(productsRe, productsBlock);

const variantsRe = /const VARIANTS\s*=\s*\{[^\n]*\};/;
if (!variantsRe.test(html)) {
  console.error('❌ Could not find VARIANTS object in index.html');
  process.exit(1);
}
html = html.replace(variantsRe, variantsBlock);

// ───── Inject build-time flags (mode + maintenance) ─────
function flagsScript(mode, maintenance) {
  return `<script>
  // Build-time flags. Live page sets mode='live'; /testing/ sets mode='test'.
  window.AUREATE_MODE = ${JSON.stringify(mode)};
  window.AUREATE_MAINTENANCE = ${maintenance ? 'true' : 'false'};
</script>`;
}
const FLAGS_MARKER = /<!-- @@BUILD_FLAGS@@ -->[\s\S]*?(?=<\/head>|<script src="https:\/\/identity\.netlify\.com)/;
// Match the marker through any prior generated flags block.
const flagsRe = /<!-- @@BUILD_FLAGS@@ -->(\s*<script>[\s\S]*?<\/script>)?/;

const maintenance = process.env.MAINTENANCE_MODE === 'true';

const liveHtml = html.replace(flagsRe, '<!-- @@BUILD_FLAGS@@ -->\n' + flagsScript('live', maintenance));
fs.writeFileSync(INDEX, liveHtml);

// Mirror site for owner test purchases. Always shop-visible (maintenance flag
// not honored) so QA work isn't blocked when the public site is down.
const testHtml = html.replace(flagsRe, '<!-- @@BUILD_FLAGS@@ -->\n' + flagsScript('test', false));
const TESTING_DIR = path.join(ROOT, 'testing');
fs.mkdirSync(TESTING_DIR, { recursive: true });
fs.writeFileSync(path.join(TESTING_DIR, 'index.html'), testHtml);

// ───── Write data/products.json (slim Stripe-ready) ─────
fs.mkdirSync(path.dirname(OUT_PROD), { recursive: true });
const slimProducts = products.map(p => ({
  id: p.id,
  name: p.name,
  price: p.price,
  image: p.image || '',
}));
fs.writeFileSync(OUT_PROD, JSON.stringify(slimProducts, null, 2));

// ───── Write data/variant-prices.clean.json (server variant validation) ─────
const variantsForServer = {};
for (const p of products) {
  variantsForServer[p.id] = (p.variants || []).map(v => ({
    n: v.name,
    p: typeof v.price === 'number' ? v.price : 0,
    a: !!v.available,
    i: v.image || '',
  }));
}
fs.writeFileSync(OUT_VAR, JSON.stringify(variantsForServer, null, 2));

const hidden = allProducts.length - products.length;
console.log(
  `✅ Built ${products.length} products → index.html, data/products.json, data/variant-prices.clean.json` +
    (hidden ? ` (${hidden} hidden as sold)` : '')
);
